---
- name: Add a user
  hosts: all
  gather_facts: false
  vars:
    - username : awx
    - password : Awx123!
  tasks:
    - name: Add User
      win_user:
        name: "{{ username }}"
        password: "{{ password }}"
        state: present
